name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Frontend setup
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          echo "API URL is: $NEXT_PUBLIC_API_URL"
          NEXT_PUBLIC_API_URL=https://dummyjson.com npm run build

      # Backend setup
      - name: Install backend dependencies
        run: |
          cd backend
          pip install fastapi uvicorn
